export const COLORS = {
  GRAY: '#5A5A5A',
  LIGHT_GRAY: '#848689',
  LIGHTEST_GRAY: '#F6F6F6',
  DARK_GRAY: '#333333',
  SEMI_BLACK: '#0B0C10',
  MARINE: '#3AAFA9',
  BORDER: '#f0f0f0',
  ORANGE: '#EFA507',
  RED: '#E84643',
  LIGHT_RED: '#F77A7A',
  OKAY_GREEN: '#82C91F',
  HIGHLIGHT_MARINE: '#7AF7CD',
  DARK_BLUE: '#084A83',
  BLUE: '#70ACDF',
  LIGHT_BLUE: '#C6E5F3',
};

export const ROUTES_KEYS = {
  HOME: '/',
  TECHNOLOGIES: '/technologies',
  CONTACT_US: '/contact',
  NANEOS: '/naneos',
  POLYIPNOS: '/polyipnos',
  ENLIT: '/enlit',
  UCNPS: '/naneos/UCNPs',
  NANO_PEROVSKITE: '/naneos/nano-perovskite',
  ORGANIC: '/naneos/organic',
  GLOW_PARTICLES: '/polyipnos/glow-particles',
  BLACK_INKS: '/polyipnos/black-inks',
  ABOUT: '/about',
  ANTI_DUST_COATINGS: '/enlit/anti-dust-coatings',
};
